export type AssistantDestination = "quote" | "gallery" | "financing" | "careers" | "contact";
export interface AssistantReply { text: string; destination?: AssistantDestination; actionLabel?: string; refused?: boolean; }
const MAX_INPUT_LENGTH = 600;
const normalize = (value: string) => value.trim().replace(/\s+/g, " ").slice(0, MAX_INPUT_LENGTH);
const includesAny = (value: string, terms: string[]) => terms.some((term) => value.includes(term));

/** Public deterministic guidance: deliberately has no app state, auth, tools, secrets, or private APIs. */
export function answerSiteQuestion(rawQuestion: string): AssistantReply {
  const question = normalize(rawQuestion); const lower = question.toLowerCase();
  if (!question) return { text: "Please enter a question about services, estimates, financing resources, careers, the podcast, or contacting David’s Contracting." };
  if (includesAny(lower,["ignore previous","ignore instructions","system prompt","developer message","reveal prompt","jailbreak","execute code","run command","tool call","api key","environment variable"])) return {text:"I can’t follow instructions that attempt to change my rules, expose internal instructions, or run software. I can still help with David’s Contracting services and public website features.",refused:true};
  if (includesAny(lower,["owner password","admin password","login credential","session token","bypass login","grant access","dashboard access","employee record","employee pay","applicant record","resume","crm data","customer list","customer data","list every customer","private lead","private information","dashboard data"])) return {text:"I can’t access or disclose Owner, Developer, employee, applicant, customer, CRM, credential, or other private information. Authorized team members must use the protected dashboard.",refused:true};
  if (includesAny(lower,["medical diagnosis","legal advice","investment advice","credit approval","approve my credit","credit decision","guarantee financing","politics","write malware","hack","weapon"])) return {text:"That request is outside this project assistant’s scope. I can provide general information about David’s Contracting services, estimates, financing resources, careers, the podcast, or contact options.",refused:true};
  if (includesAny(lower,["estimate","price","cost","budget","quote","how much"])) return {text:"The Estimate Builder can organize your project by service and selected tasks. Its result is a planning range—not a binding quote—because site conditions, measurements, materials, permits, and final scope require human review.",destination:"quote",actionLabel:"Open Estimate Builder"};
  if (includesAny(lower,["finance","financing","loan","payment plan","afford","funding","grant"])) return {text:"The Financing page lists neutral public and private resources. David’s Contracting does not make credit decisions or promise approval. Prepare an estimate first, then use the inquiry form so the Owner can understand your project and budget questions.",destination:"financing",actionLabel:"Explore financing resources"};
  if (includesAny(lower,["job","career","apply","application","laborer","work for","hiring"])) return {text:"The Careers page accepts applications for General Laborer and Contracting Work opportunities. Applications receive human review; automated scores are decision support and do not make hiring decisions.",destination:"careers",actionLabel:"Visit Careers"};
  if (includesAny(lower,["podcast","foundation first","episode","livestream","live stream"])) return {text:"Foundation First shares construction guidance, homeowner education, project stories, and contractor insights. Use the Podcast page in the main navigation to browse episodes and upcoming broadcast dates."};
  if (includesAny(lower,["gallery","photos","examples","past work","portfolio"])) return {text:"The Gallery presents published project examples and media selected by David’s Contracting. Project availability, exact scope, and results vary by property.",destination:"gallery",actionLabel:"View Gallery"};
  if (includesAny(lower,["service","remodel","repair","roof","kitchen","bathroom","deck","floor","paint","drywall","electrical","plumbing","contractor"])) return {text:"David’s Contracting supports residential repair, improvement, remodeling, and general contracting needs. Describe the area, desired work, visible damage, preferred timing, and whether you need budget guidance. Final scope and trade requirements need team confirmation.",destination:"quote",actionLabel:"Plan your project"};
  if (includesAny(lower,["contact","call","phone","email","appointment","consultation","talk to","human"])) return {text:"Use the Contact page to request a conversation. I never submit or store details from this chat automatically; information is captured only after you open the form, provide it, and explicitly consent.",destination:"contact",actionLabel:"Request human follow-up"};
  return {text:"I’m here for questions about David’s Contracting services, project planning, estimates, financing resources, careers, the gallery, Foundation First, and contacting the team. Tell me which of those you’re working on."};
}
export const SITE_ASSISTANT_MAX_INPUT = MAX_INPUT_LENGTH;
