const crmRecords = [
  {
    id: "crm-001",
    source: "staff-estimate",
    client: {
      firstName: "Marlena",
      lastName: "Brooks",
      address: "1147 N Linden Ave",
      city: "Decatur",
      state: "IL",
      zip: "62526",
      email: "marlena.brooks@example.com",
      phone: "217-555-0124",
      budget: 9800,
      emergencyIssues: "Rear bedroom ceiling stain and active roof leak after storms.",
      requestedJobs: "Roof repair, bedroom ceiling paint, hallway drywall patch",
      date: "2026-04-18",
      jobStatus: "Prospecting/Negotiating",
      declineReason: "",
      declineOtherReason: "",
      notes:
        "Interested in fast repair first, then possible full roof replacement later this year. Wants help checking city assistance programs.",
      paymentCollected: false,
      paymentAmount: 0,
      assignedRep: "David Carter",
      aidSuggestions: ["Decatur Roof Replacement Program", "Illinois Home Weatherization Assistance Program"],
      consentEmailContact: true,
      consentSmsContact: true,
      consentMarketing: false,
      consultationRequested: true,
      consultationDate: "2026-05-07",
      consultationTime: "10:30",
      consultationNotes: "Wants an onsite roof leak assessment before full quote approval.",
      consultationStatus: "Confirmed",
    },
    quoteHistory: [],
    paymentDue: 0,
    lastContactedAt: "2026-05-01",
    nextFollowUpAt: "2026-05-06",
    invoiceStatus: "Open",
    crewLead: "D. Carter",
    documentation: ["roof-leak-photos.zip", "insurance-note.txt"],
  },
  {
    id: "crm-002",
    source: "staff-estimate",
    client: {
      firstName: "Harold",
      lastName: "Reed",
      address: "2339 E Prairie Ave",
      city: "Decatur",
      state: "IL",
      zip: "62521",
      email: "harold.reed@example.com",
      phone: "217-555-0183",
      budget: 6500,
      emergencyIssues: "None, but the kitchen floor is soft near the sink.",
      requestedJobs: "LVP flooring install, subfloor patch, faucet replacement",
      date: "2026-04-09",
      jobStatus: "In-Progress",
      declineReason: "",
      declineOtherReason: "",
      notes: "Deposit collected. Wants work completed before family event on May 20.",
      paymentCollected: true,
      paymentAmount: 1800,
      assignedRep: "David Carter",
      aidSuggestions: [],
      consentEmailContact: true,
      consentSmsContact: true,
      consentMarketing: false,
      consultationRequested: true,
      consultationDate: "2026-05-08",
      consultationTime: "13:00",
      consultationNotes: "Follow-up measurement visit before start date.",
      consultationStatus: "Requested",
    },
    quoteHistory: [],
    paymentDue: 4200,
    lastContactedAt: "2026-05-03",
    nextFollowUpAt: "2026-05-08",
    invoiceStatus: "Partially Paid",
    crewLead: "M. Lewis",
    documentation: ["kitchen-floor-plan.pdf", "deposit-receipt.pdf"],
  },
  {
    id: "crm-003",
    source: "staff-estimate",
    client: {
      firstName: "Yvette",
      lastName: "Johnson",
      address: "809 W King St",
      city: "Decatur",
      state: "IL",
      zip: "62522",
      email: "yvette.johnson@example.com",
      phone: "217-555-0166",
      budget: 2200,
      emergencyIssues: "Furnace keeps short cycling and thermostat is failing.",
      requestedJobs: "HVAC diagnostic, thermostat replacement, weatherstripping",
      date: "2026-03-29",
      jobStatus: "Completed",
      declineReason: "",
      declineOtherReason: "",
      notes: "Veteran household. Asked about heating assistance resources.",
      paymentCollected: true,
      paymentAmount: 2250,
      assignedRep: "David Carter",
      aidSuggestions: ["Empowerment Opportunity Center / CSBG & LIHEAP Intake", "Macon County Veterans Assistance"],
      consentEmailContact: true,
      consentSmsContact: false,
      consentMarketing: false,
      consultationRequested: false,
      consultationDate: "",
      consultationTime: "",
      consultationNotes: "",
      consultationStatus: "Completed",
    },
    quoteHistory: [],
    paymentDue: 0,
    lastContactedAt: "2026-04-15",
    nextFollowUpAt: "2026-06-01",
    invoiceStatus: "Paid",
    crewLead: "D. Carter",
    documentation: ["hvac-diagnostic-sheet.pdf"],
  },
];

const historicalJobs = [
  {
    id: "job-2026-001",
    clientName: "Angela Morris",
    projectTitle: "Interior repaint + trim refresh",
    categories: ["painting"],
    notes: "1,280 sq ft occupied home. Needed extra masking and stain-blocking in one bedroom.",
    quoteTotal: 4680,
    status: "Completed",
    generatedAt: "2026-02-13T16:30:00.000Z",
  },
  {
    id: "job-2026-002",
    clientName: "Terrence Hall",
    projectTitle: "LVP and subfloor stabilization",
    categories: ["flooring", "handiwork"],
    notes: "Soft kitchen entry, 312 sq ft LVP, quarter-round and threshold transitions included.",
    quoteTotal: 6150,
    status: "Completed",
    generatedAt: "2026-03-10T13:45:00.000Z",
  },
  {
    id: "job-2026-003",
    clientName: "Naomi Fields",
    projectTitle: "Roof repair and soffit patch",
    categories: ["roofing"],
    notes: "Localized shingle blow-off, vent boot repair, and 18 linear feet of soffit replacement.",
    quoteTotal: 2380,
    status: "Completed",
    generatedAt: "2026-03-28T15:20:00.000Z",
  },
  {
    id: "job-2026-004",
    clientName: "Bennie Foster",
    projectTitle: "Punch-list accessibility fixes",
    categories: ["handiwork", "electrical-hvac"],
    notes: "Grab bar install, light fixture swap, weatherstripping, smoke detector replacements.",
    quoteTotal: 1545,
    status: "Completed",
    generatedAt: "2026-04-03T18:10:00.000Z",
  },
];

const reminders = [
  {
    id: "rem-001",
    clientName: "Marlena Brooks",
    note: "Call about roof assistance application timing and finalize leak repair scope.",
    dueDate: "2026-05-06",
    priority: "High",
  },
  {
    id: "rem-002",
    clientName: "Harold Reed",
    note: "Confirm material pickup and crew arrival for kitchen flooring start.",
    dueDate: "2026-05-08",
    priority: "Medium",
  },
  {
    id: "rem-003",
    clientName: "Yvette Johnson",
    note: "30-day satisfaction follow-up and spring AC maintenance offer.",
    dueDate: "2026-06-01",
    priority: "Low",
  },
];

const seedAppState = {
  settings: {
    repProfile: {
      repName: "David Carter",
      companyName: "David's Contracting",
      phone: "217-542-4566",
      email: "student.jayla1985@gmail.com",
      title: "Owner / Estimator",
    },
    adminEmail: "owner@davidscontracting.local",
    adminPassword: "",
    staffEmail: "estimator@davidscontracting.local",
    staffPassword: "",
    serviceAreaZip: "62526",
    aiProvider: "heuristic",
    googleAppsScriptUrl: "",
    aiWebhookUrl: "",
    emailWebhookUrl: "",
    openAiApiKey: "",
    openAiModel: "gpt-5.4-mini",
    openAiSearchModel: "gpt-4o-mini-search-preview",
    openAiTranscriptionModel: "gpt-4o-mini-transcribe",
    lowMarkupPct: 0.14,
    highMarkupPct: 0.22,
    taxPct: 0.08,
    travelFee: 95,
    defaultQuoteValidityDays: 14,
    standardDepositPct: 0.35,
    largeJobDepositPct: 0.45,
    largeJobThreshold: 5000,
    defaultContingencyPct: 0.05,
    availabilitySchedule: [
      { day: "Monday", enabled: true, start: "08:00", end: "17:00" },
      { day: "Tuesday", enabled: true, start: "08:00", end: "17:00" },
      { day: "Wednesday", enabled: true, start: "08:00", end: "17:00" },
      { day: "Thursday", enabled: true, start: "08:00", end: "17:00" },
      { day: "Friday", enabled: true, start: "08:00", end: "17:00" },
      { day: "Saturday", enabled: true, start: "09:00", end: "13:00" },
      { day: "Sunday", enabled: false, start: "09:00", end: "12:00" },
    ],
    consultationBlackoutDates: [],
    hasAdminPassword: true,
    hasStaffPassword: true,
    hasOpenAiApiKey: false,
    hasAiWebhook: false,
    hasEmailWebhook: false,
    hasGoogleSheetsSync: false,
  },
  crmRecords,
  reminders,
  historicalJobs,
};

export const starterAdminPassword = "BuiltOnPurpose30!";
export const starterStaffPassword = "FieldReady30!";

export const createSeedAppState = () => JSON.parse(JSON.stringify(seedAppState));
