import { FormEvent, useMemo, useState } from "react";
import { Eye, EyeOff, Film, ImagePlus, Pencil, Plus, Trash2 } from "lucide-react";
import { GalleryProject } from "../types";

interface Props { projects: GalleryProject[]; onSave: (projects: GalleryProject[]) => Promise<void>; }
const blank = () => ({ title:"", propertyLabel:"", address:"", city:"Decatur", state:"IL", projectType:"", purpose:"Residential improvement", summary:"", completedAt:"", coverImageUrl:"", published:false, displayOrder:0 });
const slugify = (value:string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

export function GalleryManager({ projects, onSave }: Props) {
  const [selectedId,setSelectedId]=useState<string|null>(null); const [draft,setDraft]=useState(blank());
  const [media,setMedia]=useState<GalleryProject["media"]>([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  const sorted=useMemo(()=>[...projects].sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0)||b.updatedAt.localeCompare(a.updatedAt)),[projects]);
  const edit=(p:GalleryProject)=>{setSelectedId(p.id);setDraft({title:p.title,propertyLabel:p.propertyLabel??"",address:p.address??"",city:p.city,state:p.state,projectType:p.projectType,purpose:p.purpose??"",summary:p.summary,completedAt:p.completedAt,coverImageUrl:p.coverImageUrl,published:p.published,displayOrder:p.displayOrder??0});setMedia(p.media);setMessage("");};
  const reset=()=>{setSelectedId(null);setDraft(blank());setMedia([]);setMessage("");};
  const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setMessage("");try{const now=new Date().toISOString();const existing=projects.find(p=>p.id===selectedId);const next:GalleryProject={id:existing?.id??crypto.randomUUID(),slug:slugify(draft.title),...draft,media,createdAt:existing?.createdAt??now,updatedAt:now};await onSave(existing?projects.map(p=>p.id===existing.id?next:p):[...projects,next]);setMessage("Gallery project saved.");setSelectedId(next.id);}catch(err){setMessage(err instanceof Error?err.message:"Unable to save project.");}finally{setSaving(false);}};
  const remove=async(id:string)=>{if(!window.confirm("Remove this gallery project?"))return;setSaving(true);try{await onSave(projects.filter(p=>p.id!==id));if(selectedId===id)reset();}finally{setSaving(false);}};
  const addMedia=()=>setMedia(v=>[...v,{id:crypto.randomUUID(),type:"image",url:"",thumbnailUrl:"",alt:"",caption:"",attribution:""}]);
  const updateMedia=(id:string,patch:Partial<GalleryProject["media"][number]>)=>setMedia(v=>v.map(m=>m.id===id?{...m,...patch}:m));
  return <section className="gallery-manager">
    <header className="gallery-manager__header"><div><p className="eyebrow">Gallery Uploads</p><h2>Build polished, privacy-conscious project stories.</h2><p>Add property or general-purpose collections, media credits, captions, ordering, and publication status.</p></div><button className="brand-button" type="button" onClick={reset}><Plus size={17}/> New project</button></header>
    <div className="gallery-manager__layout"><aside className="gallery-manager__list"><strong>{projects.length} projects</strong>{sorted.map(p=><article className={selectedId===p.id?"is-active":""} key={p.id}><button type="button" onClick={()=>edit(p)}><span>{p.coverImageUrl?<img src={p.coverImageUrl} alt=""/>:<ImagePlus/>}</span><div><b>{p.title}</b><small>{p.city}, {p.state} · {p.published?"Published":"Draft"}</small></div></button><button type="button" aria-label={`Delete ${p.title}`} onClick={()=>void remove(p.id)}><Trash2 size={15}/></button></article>)}</aside>
      <form className="gallery-editor" onSubmit={save}><div className="gallery-editor__title"><h3>{selectedId?"Edit project":"Create project"}</h3><label className="publish-toggle">{draft.published?<Eye size={17}/>:<EyeOff size={17}/>}<input type="checkbox" checked={draft.published} onChange={e=>setDraft(d=>({...d,published:e.target.checked}))}/> Publish publicly</label></div>
      <div className="gallery-editor__grid"><label>Project title<input required value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></label><label>Project type<input required placeholder="Kitchen, roofing, restoration…" value={draft.projectType} onChange={e=>setDraft(d=>({...d,projectType:e.target.value}))}/></label><label>Property / collection label<input placeholder="Use a privacy-safe label" value={draft.propertyLabel} onChange={e=>setDraft(d=>({...d,propertyLabel:e.target.value}))}/></label><label>Purpose<select value={draft.purpose} onChange={e=>setDraft(d=>({...d,purpose:e.target.value}))}><option>Residential improvement</option><option>Commercial improvement</option><option>General portfolio</option><option>Before and after</option></select></label><label>Private address<input value={draft.address} onChange={e=>setDraft(d=>({...d,address:e.target.value}))}/><small>Stored for owner reference; public gallery only displays city/state.</small></label><label>City<input required value={draft.city} onChange={e=>setDraft(d=>({...d,city:e.target.value}))}/></label><label>State<input required maxLength={2} value={draft.state} onChange={e=>setDraft(d=>({...d,state:e.target.value.toUpperCase()}))}/></label><label>Completion date<input type="date" value={draft.completedAt} onChange={e=>setDraft(d=>({...d,completedAt:e.target.value}))}/></label><label>Display order<input type="number" value={draft.displayOrder} onChange={e=>setDraft(d=>({...d,displayOrder:Number(e.target.value)}))}/></label><label className="gallery-editor__wide">Summary<textarea required value={draft.summary} onChange={e=>setDraft(d=>({...d,summary:e.target.value}))}/></label><label className="gallery-editor__wide">Cover image URL<input type="url" placeholder="https://images.pexels.com/…" value={draft.coverImageUrl} onChange={e=>setDraft(d=>({...d,coverImageUrl:e.target.value}))}/></label></div>
      <div className="gallery-media"><header><div><h3>Images & videos</h3><p>Use direct HTTPS media URLs. Add descriptive alt text and source attribution.</p></div><button type="button" className="ghost-button" onClick={addMedia}><ImagePlus size={17}/> Add media</button></header>{media.map((m,index)=><article key={m.id}><span className="gallery-media__number">{index+1}</span><label>Type<select value={m.type} onChange={e=>updateMedia(m.id,{type:e.target.value as "image"|"video"})}><option value="image">Image</option><option value="video">Video</option></select></label><label>Media URL<input required type="url" value={m.url} onChange={e=>updateMedia(m.id,{url:e.target.value})}/></label><label>Thumbnail URL<input type="url" value={m.thumbnailUrl} onChange={e=>updateMedia(m.id,{thumbnailUrl:e.target.value})}/></label><label>Accessible description<input required value={m.alt} onChange={e=>updateMedia(m.id,{alt:e.target.value})}/></label><label>Caption<input value={m.caption} onChange={e=>updateMedia(m.id,{caption:e.target.value})}/></label><label>Source / attribution<input placeholder="Photo by … on Pexels" value={m.attribution??""} onChange={e=>updateMedia(m.id,{attribution:e.target.value})}/></label><button type="button" className="icon-button" aria-label="Remove media" onClick={()=>setMedia(v=>v.filter(x=>x.id!==m.id))}><Trash2 size={16}/></button></article>)}</div>
      <footer className="gallery-editor__actions">{message&&<span role="status">{message}</span>}<button className="brand-button" disabled={saving}>{saving?"Saving…":<><Pencil size={16}/> Save project</>}</button></footer></form></div>
  </section>;
}
