import { Plus, Radio, Save, Trash2 } from "lucide-react";
import { PodcastEpisode, PodcastEvent } from "../types";

export function PodcastManager({ episodes, events, onSave }: { episodes: PodcastEpisode[]; events: PodcastEvent[]; onSave: (patch: { podcastEpisodes?: PodcastEpisode[]; podcastEvents?: PodcastEvent[] }) => Promise<void> }) {
  const addEpisode=()=>void onSave({podcastEpisodes:[...episodes,{id:crypto.randomUUID(),episodeNumber:episodes.length+1,title:"New episode",description:"Add the episode summary.",format:"Audio & Video",mediaUrl:"",thumbnailUrl:"",duration:"30 min",publishedAt:"",status:"Draft",featured:false}]});
  const patchEpisode=(id:string,patch:Partial<PodcastEpisode>)=>void onSave({podcastEpisodes:episodes.map(item=>item.id===id?{...item,...patch}:item)});
  const addEvent=()=>void onSave({podcastEvents:[...events,{id:crypto.randomUUID(),title:"New live broadcast",startsAt:"",durationMinutes:45,format:"Live stream",watchUrl:"",description:"",published:false}]});
  const patchEvent=(id:string,patch:Partial<PodcastEvent>)=>void onSave({podcastEvents:events.map(item=>item.id===id?{...item,...patch}:item)});
  return <section className="podcast-manager"><header><div><p className="eyebrow">Podcast Studio</p><h2>Foundation First publishing</h2><p>Manage the public archive, media playback, featured episode, and upcoming broadcast calendar.</p></div><button className="primary-button" onClick={addEpisode}><Plus size={16}/> New episode</button></header>
    <h3>Episodes</h3><div className="podcast-manager__list">{episodes.map(item=><article key={item.id}><span className="podcast-manager__number">{String(item.episodeNumber).padStart(2,"0")}</span><div className="podcast-manager__fields"><label>Title<input value={item.title} onChange={e=>patchEpisode(item.id,{title:e.target.value})}/></label><label>Description<textarea value={item.description} onChange={e=>patchEpisode(item.id,{description:e.target.value})}/></label><label>Status<select value={item.status} onChange={e=>patchEpisode(item.id,{status:e.target.value as PodcastEpisode["status"]})}><option>Draft</option><option>Scheduled</option><option>Published</option></select></label><label>Format<select value={item.format} onChange={e=>patchEpisode(item.id,{format:e.target.value as PodcastEpisode["format"]})}><option>Audio</option><option>Video</option><option>Audio & Video</option></select></label><label>Media URL<input type="url" value={item.mediaUrl} onChange={e=>patchEpisode(item.id,{mediaUrl:e.target.value})}/></label><label>Thumbnail URL<input type="url" value={item.thumbnailUrl} onChange={e=>patchEpisode(item.id,{thumbnailUrl:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={item.featured} onChange={e=>void onSave({podcastEpisodes:episodes.map(x=>({...x,featured:x.id===item.id?e.target.checked:false}))})}/> Feature publicly</label></div><button className="icon-button" aria-label={`Delete ${item.title}`} onClick={()=>void onSave({podcastEpisodes:episodes.filter(x=>x.id!==item.id)})}><Trash2 size={16}/></button></article>)}</div>
    <div className="podcast-manager__schedule-title"><div><h3><Radio size={19}/> Broadcast calendar</h3><p>Only published events appear on the public page.</p></div><button className="ghost-button" onClick={addEvent}><Plus size={16}/> Add date</button></div><div className="podcast-manager__events">{events.map(item=><article key={item.id}><label>Event title<input value={item.title} onChange={e=>patchEvent(item.id,{title:e.target.value})}/></label><label>Date & time<input type="datetime-local" value={item.startsAt} onChange={e=>patchEvent(item.id,{startsAt:e.target.value})}/></label><label>Broadcast URL<input type="url" value={item.watchUrl} onChange={e=>patchEvent(item.id,{watchUrl:e.target.value})}/></label><label>Description<textarea value={item.description} onChange={e=>patchEvent(item.id,{description:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={item.published} onChange={e=>patchEvent(item.id,{published:e.target.checked})}/> Public</label><button className="icon-button" aria-label={`Delete ${item.title}`} onClick={()=>void onSave({podcastEvents:events.filter(x=>x.id!==item.id)})}><Trash2 size={16}/></button></article>)}</div><p className="podcast-manager__hint"><Save size={15}/> Changes save securely as fields are updated.</p>
  </section>;
}
